import sanitizeHtml from 'sanitize-html';

const SAFE_CSS_VAR = /^var\(\s*--[a-zA-Z][a-zA-Z0-9_-]*\s*\)$/;

/** Sanitize TipTap HTML for safe public rendering. */
export function sanitizeArticleHtml(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: [
      ...sanitizeHtml.defaults.allowedTags,
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'img',
      'figure',
      'figcaption',
      'table',
      'thead',
      'tbody',
      'tfoot',
      'tr',
      'th',
      'td',
      'pre',
      'code',
      'blockquote',
      'hr',
      'iframe',
      'video',
      'source',
      'span',
      'div',
      'mark',
      's',
      'strike',
      'u',
      'sub',
      'sup',
      'label',
      'input',
    ],
    allowedAttributes: {
      ...(sanitizeHtml.defaults.allowedAttributes ?? {}),
      a: ['href', 'target', 'rel', 'title', 'style', 'class'],
      img: [
        'src',
        'srcset',
        'alt',
        'title',
        'width',
        'height',
        'loading',
        'decoding',
        'style',
        'class',
      ],
      iframe: [
        'src',
        'title',
        'width',
        'height',
        'allow',
        'allowfullscreen',
        'frameborder',
        'style',
        'class',
      ],
      video: [
        'src',
        'controls',
        'autoplay',
        'loop',
        'muted',
        'poster',
        'width',
        'height',
        'style',
        'class',
      ],
      source: ['src', 'type'],
      p: ['style', 'class', 'dir'],
      span: ['style', 'class', 'dir', 'data-color'],
      div: ['style', 'class', 'dir'],
      mark: ['style', 'class', 'data-color'],
      h1: ['style', 'class', 'dir'],
      h2: ['style', 'class', 'dir'],
      h3: ['style', 'class', 'dir'],
      h4: ['style', 'class', 'dir'],
      h5: ['style', 'class', 'dir'],
      h6: ['style', 'class', 'dir'],
      ul: ['style', 'class', 'dir', 'data-type'],
      ol: ['style', 'class', 'dir', 'data-type', 'start'],
      li: ['style', 'class', 'dir', 'data-type', 'data-checked'],
      blockquote: ['style', 'class', 'dir'],
      pre: ['style', 'class'],
      code: ['style', 'class'],
      hr: ['style', 'class'],
      figure: ['style', 'class'],
      figcaption: ['style', 'class'],
      table: ['class', 'style', 'border'],
      thead: ['style', 'class'],
      tbody: ['style', 'class'],
      tfoot: ['style', 'class'],
      tr: ['style', 'class'],
      th: ['colspan', 'rowspan', 'scope', 'style', 'class'],
      td: ['colspan', 'rowspan', 'style', 'class'],
      strong: ['style', 'class'],
      em: ['style', 'class'],
      b: ['style', 'class'],
      i: ['style', 'class'],
      s: ['style', 'class'],
      strike: ['style', 'class'],
      u: ['style', 'class'],
      sub: ['style', 'class'],
      sup: ['style', 'class'],
      br: ['class'],
      label: ['class', 'contenteditable'],
      input: ['type', 'checked', 'disabled'],
      '*': ['class', 'id', 'dir', 'lang', 'aria-label', 'style'],
    },
    allowedStyles: {
      '*': {
        color: [
          SAFE_CSS_VAR,
          /^#([0-9a-fA-F]{3,8})$/i,
          /^rgba?\([^)]*\)$/i,
          /^hsla?\([^)]*\)$/i,
          /^inherit$/,
          /^currentColor$/i,
          /^transparent$/i,
        ],
        'background-color': [
          SAFE_CSS_VAR,
          /^#([0-9a-fA-F]{3,8})$/i,
          /^rgba?\([^)]*\)$/i,
          /^hsla?\([^)]*\)$/i,
          /^transparent$/i,
          /^inherit$/i,
        ],
        'text-align': [/^(left|right|center|justify|start|end)$/],
        'text-indent': [/^-?\d+(\.\d+)?(px|em|rem|%)$/],
        'font-size': [/^\d+(\.\d+)?(px|em|rem|%)$/],
        'line-height': [/^\d+(\.\d+)?$/, /^\d+(\.\d+)?(px|em|rem)$/],
        direction: [/^(rtl|ltr)$/],
        width: [/^\d+(\.\d+)?(px|%|em|rem)$/],
        height: [/^\d+(\.\d+)?(px|%|em|rem)$/],
        'max-width': [/^\d+(\.\d+)?(px|%|em|rem)$/],
        'vertical-align': [/^(sub|super|baseline|middle|top|bottom)$/],
        'padding-inline-start': [/^\d+(\.\d+)?(px|em|rem)$/],
        'margin-inline-start': [/^-?\d+(\.\d+)?(px|em|rem)$/],
      },
    },
    allowedSchemes: ['http', 'https', 'mailto', 'tel'],
    allowedSchemesByTag: {
      img: ['http', 'https', 'data'],
      source: ['http', 'https', 'data'],
    },
    allowedIframeHostnames: [
      'www.youtube.com',
      'youtube.com',
      'youtu.be',
      'player.vimeo.com',
    ],
    allowProtocolRelative: false,
    transformTags: {
      a: sanitizeHtml.simpleTransform(
        'a',
        { rel: 'noopener noreferrer nofollow' },
        true,
      ),
    },
  });
}

export function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function truncateText(text: string, max = 160): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 1).trimEnd()}…`;
}
